### ISSUE TITLE
[Bug]: Wrong GPU (1st one) used when STDIN is closed

### ISSUE THREAD

**Issue by eero-t** [intel/libva#643]
Setup:
* Multiple GPUs where first one is NOT the correct one
* Latest media stack

Use-case:
* Run program that uses libva so that STDIN is closed, and tell it to use some other GPU than the first one, e.g:
  `vainfo --display drm --device /dev/dri/renderD129`

Expected outcome:
* Program runs fine, like it does when STDIN is e.g. mapped to `/dev/null`:
```
libva info: VA-API version 1.16.0
libva info: User environment variable requested driver 'iHD'
libva info: Trying to open /usr/local/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_16
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.16 (libva 2.12.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 22.5.4 (e461c05)
vainfo: Supported profile and entrypoints
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileNone                   :	VAEntrypointStats
...
      VAProfileHEVCSccMain444_10      :	VAEntrypointVLD
      VAProfileHEVCSccMain444_10      :	VAEntrypointEncSliceLP
```

Actual outcome:
* Program tries to use first GPU (`/dev/dri/renderD128`), and fails:
```
libva info: VA-API version 1.16.0
libva info: User environment variable requested driver 'iHD'
libva info: Trying to open /usr/local/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_16
libva error: /usr/local/lib/dri/iHD_drv_video.so init failed
libva info: va_openDriver() returns 2
vaInitialize failed with error code 2 (resource allocation failed),exit
```

Same happens also when using e.g. oneVPL, regardless of whether one specifies the device for oneVPL, or lets oneVPL to choose suitable one.  Media-driver / libva just does not respect what OneVPL specifies.

Attached is source for a test program that can be used to test this:
* Works: `vpl-tester -null-in  /usr/bin/vainfo --display drm --device /dev/dri/renderD129`  # STDIN mapped to /dev/null
* Fails: `vpl-tester -close-in  /usr/bin/vainfo --display drm --device /dev/dri/renderD129`  # STDIN closed

Test program (Golang) sources: [vpl-tester.go](https://github.com/intel/libva/files/9802692/vpl-tester.go.txt)

**Comment by eero-t** [comment]
Strace shows that fail is returned after wrong GPU is tried.  Following is outcome from a 2-GPU device, where Docker containerization is used to make only second GPU visible (similarly to how things would work e.g. in Kubernetes managed cloud with Intel GPU plugin):
```
# docker run -it --rm --user root --network none --cap-drop ALL --cap-add SYS_PTRACE \
  --device /dev/dri/renderD129:/dev/dri/renderD129:rw registry/project/vpl-tester:latest \
  strace -f -e file /vpl-tester -close-in /usr/bin/vainfo --display drm --device /dev/dri/renderD129
...
libva info: Found init function __vaDriverInit_1_16
[pid    15] newfstatat(AT_FDCWD, "/dev/dri/renderD128", 0x7fff5de4c150, 0) = -1 ENOENT (No such file or directory)
libva error: /usr/local/lib/dri/iHD_drv_video.so init failed
libva info: va_openDriver() returns 2
vaInitialize failed with error code 2 (resource allocation failed),exit
[pid    15] +++ exited with 3 +++
```

I think the issue is that when STDIN is closed by the VA-API process parent, file descriptor 0 gets **re-used** as next free file descriptor, and can be anything:
```
$ ./vpl-tester -close-in /usr/bin/ls -l /proc/self/fd
2022/10/17 15:00:28 stdin closed
2022/10/17 15:00:28 stdout/stderr mapped to parent stdout/stderr
2022/10/17 15:00:28 Running: [/usr/bin/ls -l /proc/self/fd]
total 0
lr-x------ 1 nobody 109 64 Oct 17 15:00 0 -> /proc/12/fd
lrwx------ 1 nobody 109 64 Oct 17 15:00 1 -> /dev/pts/0
lrwx------ 1 nobody 109 64 Oct 17 15:00 2 -> /dev/pts/0
2022/10/17 15:00:28 [/usr/bin/ls -l /proc/self/fd] = 0 (0.000665s)
```

=> In a library, checking file descriptor values against zero, or expecting specific file descriptor values to correspond to specific kinds of files, is wrong.

(Intel GPUs can be used in server environments, and those are often headless.  Actual network service functionality is increasingly built in safer languages like Go, which then call external programs to do the actual work.  Leaving unused FDs closed in child processes seems natural at least in Go.)

**Comment by eero-t** [comment]
@dvrogozh Is there any progress with this?

**Comment by XinfengZhang** [comment]
it is a driver issue,  @eero-t  could you help to try change https://github.com/intel/media-driver/blob/master/media_driver/linux/common/ddi/media_libva.cpp#L1572
from:     if(pDRMState->fd < 0 || pDRMState->fd == 0 )
to:    if(pDRMState->fd < 0 )

**Comment by dvrogozh** [comment]
@XinfengZhang : considering `fd=0` to be invalid is clearly wrong. And I guess that since `=0` is not taken (stdin is off), it was taken with open(/dev/dri/renderDxxx). Hence a problem. So, I think we definitely need a PR for the driver.

Now 2 questions:
1. Is that an actually correct assumption that libva might not be able to provide a valid FD? if yes, in which cases specifically it might not be provided?
2. If that's valid and we might not always get FD from libva, should not we just abort since we are trying to guess the device and on multi device system might get wrong?
3. Do we have any place in libva where we initialized fd=0 by default while we should initialized =-1? /I mean places like memset(0);/

**Comment by XinfengZhang** [comment]
> @XinfengZhang : considering `fd=0` to be invalid is clearly wrong. And I guess that since `=0` is not taken (stdin is off), it was taken with open(/dev/dri/renderDxxx). Hence a problem. So, I think we definitely need a PR for the driver.
> 
yes, the value of the normal fd should be non-negative , so, it should be >=0. we will  change the check just like my previous comment https://github.com/intel/libva/issues/643#issuecomment-134432847

> Now 2 questions:
> 
> 1. Is that an actually correct assumption that libva might not be able to provide a valid FD? if yes, in which cases specifically it might not be provided?

before,  if there are no DRI2 support, the DRI2 connect function will failed. but the environment LIBVA_DRIVER_NAME will ensure the process continue , even the fd is invalid 

> 2. If that's valid and we might not always get FD from libva, should not we just abort since we are trying to guess the device and on multi device system might get wrong?

you could treat it as a WA, because we have no DRI3 support before, so, the DRI connect function may failed on X-Wayland. it will make sure the HW accel will work. 

> 3. Do we have any place in libva where we initialized fd=0 by default while we should initialized =-1? /I mean places like memset(0);/

it depends, if it is drm, the fd is from application , it should be a valid one, libva will check it.  if it is X11, the fd will be initialized to -1, and get the correct one with DRI connect function .

**Comment by XinfengZhang** [comment]
it should be fixed by https://github.com/intel/media-driver/commit/1bf79a0f2da9bf3899e4567510519e0ec7d7d31d, could you have a try?

**Comment by eero-t** [comment]
> it should be fixed by [intel/media-driver@1bf79a0](https://github.com/intel/media-driver/commit/1bf79a0f2da9bf3899e4567510519e0ec7d7d31d), could you have a try?

@XinfengZhang Did you try the tester I provided?

I tested the following media stack:
- libva:    2.17.0
- GMMlib:   intel-gmmlib-22.3.3
- Media driver:    intel-media-23.1.0
- MediaSDK: intel-mediasdk-23.1.0
- oneVPL:   v2023.1.1
- VPL-GPU:  intel-onevpl-23.1.0

Which includes the indicated commit, and it still fails when STDIN is closed (i.e. device FD is zero):
```
$ strace -f -e file vpl-tester -close-in /usr/bin/vainfo --display drm --device /dev/dri/renderD129
execve("vpl-tester", ["vpl-tester", "-close-in", "/usr/bin/vainfo", "--display", "drm", "--device", "/dev/dri/renderD129"], 0x7ffea57b8c98 /* 7 vars */) = 0
...
2023/01/18 16:22:43 stdin closed
2023/01/18 16:22:43 stdout/stderr mapped to parent stdout/stderr
2023/01/18 16:22:43 Running: [/usr/bin/vainfo --display drm --device /dev/dri/renderD129]
...
[pid    15] openat(AT_FDCWD, "/dev/dri/renderD129", O_RDWR) = 0    **** <==== *****
[pid    15] newfstatat(0, "", {st_mode=S_IFCHR|0660, st_rdev=makedev(0xe2, 0x81), ...}, AT_EMPTY_PATH) = 0
[pid    15] newfstatat(AT_FDCWD, "/sys/dev/char/226:129/device/drm", {st_mode=S_IFDIR|0755, st_size=0, ...}, 0) = 0
...
libva info: VA-API version 1.17.0
libva info: User environment variable requested driver 'iHD'
libva info: Trying to open /usr/local/lib/dri/iHD_drv_video.so
[pid    15] openat(AT_FDCWD, "/usr/local/lib/dri/iHD_drv_video.so", O_RDONLY|O_CLOEXEC) = 3
...
libva info: Found init function __vaDriverInit_1_17
...
libva error: /usr/local/lib/dri/iHD_drv_video.so init failed
libva info: va_openDriver() returns 1
vaInitialize failed with error code 1 (operation failed),exit
```

This fail happens even when first (`renderD128`) GPU is specified:
```
# docker run -it --cap-drop ALL --network none --user root -v $PWD:/media --device /dev/dri/renderD128:/dev/dri/renderD128:rw media-driver-stack:2023-01-18 /media/vpl-tester -close-in /usr/bin/vainfo --display drm --device /dev/dri/renderD128
2023/01/18 16:33:59 stdin closed
2023/01/18 16:33:59 stdout/stderr mapped to parent stdout/stderr
2023/01/18 16:33:59 Running: [/usr/bin/vainfo --display drm --device /dev/dri/renderD128]
libva info: VA-API version 1.17.0
libva info: User environment variable requested driver 'iHD'
libva info: Trying to open /usr/local/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_17
libva error: /usr/local/lib/dri/iHD_drv_video.so init failed
libva info: va_openDriver() returns 1
vaInitialize failed with error code 1 (operation failed),exit
2023/01/18 16:33:59 [/usr/bin/vainfo --display drm --device /dev/dri/renderD128] = 3 (0.003463s)
```

Whereas when STDIN is mapped to `/dev/null`, all works fine:
```
# docker run -it --cap-drop ALL --network none --user root -v $PWD:/media --device /dev/dri/renderD128:/dev/dri/renderD128:rw media-driver-stack:2023-01-18 /media/vpl-tester -null-in /usr/bin/vainfo --display drm --device /dev/dri/renderD128
2023/01/18 16:35:42 stdin mapped to /dev/null
2023/01/18 16:35:42 stdout/stderr mapped to parent stdout/stderr
2023/01/18 16:35:42 Running: [/usr/bin/vainfo --display drm --device /dev/dri/renderD128]
libva info: VA-API version 1.17.0
libva info: User environment variable requested driver 'iHD'
libva info: Trying to open /usr/local/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_17
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.17 (libva 2.12.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 23.1.0 (012af72)
vainfo: Supported profile and entrypoints
      VAProfileNone                   :	VAEntrypointVideoProc
...
```

(In this case, `strace` shows open for `/dev/dri/renderD129` getting FD 3 instead of 0.)

**Comment by eero-t** [comment]
Btw.  I tried and straced also a tester for level-Zero Sysman, and an OpenCL program with this.

OpenCL program apparently had other FDs open, because device open gave larger FD than 0, and program naturally worked -> inconclusive.

Sysman got FD 0 from device open, but worked still fine.

I haven't tried this test-case with Mesa Iris / Anvil 3D drivers, but as whole Mesa project is used for so many purposes (drivers for gl, gles, vulkan, opencl, and lately even vaapi, for many different vendors), and it's so old (originates from last century), I would assume this kind of issues to have been ironed out of it long time ago.

**Comment by MicroYY** [comment]
Fixed in media driver https://github.com/intel/media-driver/commit/407bd9348 and close this issue.
Pls feel free to reopen if the issue still exist.

**Comment by eero-t** [comment]
Thanks, I validated the fix with the latest "intel-media-23.3.1" release (that contains the fix):
```
strace -f -e openat /media/vpl-tester -close-in  /usr/bin/vainfo --display drm --device /dev/dri/renderD129 | grep -e AV1 -e renderD 
2023/08/18 16:10:06 Running: [/usr/bin/vainfo --display drm --device /dev/dri/renderD129]
[pid    15] openat(AT_FDCWD, "/dev/dri/renderD129", O_RDWR) = 0
      VAProfileAV1Profile0            :	VAEntrypointVLD
2023/08/18 16:10:06 [/usr/bin/vainfo --display drm --device /dev/dri/renderD129] = 0 (0.012669s)
```
=> Opens correct device, and works although STDIN is closed (i.e. driver gets 0 as FD for the device file).

Verified with `sample_multi_transcode` that also more complex cases like transcoding work now!

----

PS. Looking at the fix commit, I think part of the blame for the issue could go to media-driver coding conventions.  I would think that with `if (fd > 0)` instead of `if (0 >= fd)`, the problem would have been easier to notice when the code was initially written.
